"""Planning's own public surface (spec section 3.4) -- the concrete
classes in `store.py`/`dag.py`/`decomposer.py` already satisfy these
shapes; this module is the documented contract other code in this
package (and a future test) is written against."""

from __future__ import annotations

from typing import Iterable, Mapping, Protocol

from .model import Scope, Step, Task
from .store import ClaimResult


class TaskStoreProtocol(Protocol):
    async def create(self, *, kind: str, description: str, origin: str, **kwargs) -> Task: ...
    async def get(self, task_id: str) -> Task | None: ...
    async def transition(self, task_id: str, status: str, *, note: str = "", attempt: bool = False,
                         expected_seq: int | None = None) -> Task: ...
    async def claim(self, task_id: str, worker_id: str, lease_seconds: float) -> ClaimResult: ...
    def children(self, parent_id: str) -> list[Task]: ...
    def ready(self, *, limit: int = 10) -> list[Task]: ...
    def unfinished(self) -> list[Task]: ...


class DependencyGraphProtocol(Protocol):
    def validate(self, task_id: str, depends_on: list[str], known: Mapping[str, Task]) -> None: ...
    def dependents_of(self, task_id: str, known: Mapping[str, Task]) -> list[str]: ...
    def is_ready(self, task: Task, known: Mapping[str, Task]) -> bool: ...


class DecomposerProtocol(Protocol):
    async def decompose(self, goal: str, files: list[str], count: int) -> list[Step]: ...
    def parse_steps(self, text: str, expected: int) -> list[Step]: ...


__all__ = ["DecomposerProtocol", "DependencyGraphProtocol", "Scope", "Step", "Task", "TaskStoreProtocol"]
