"""The shapes `service.py` composes (spec section 3.4) -- documentation
by structure, no shared base class needed since each already matches."""

from __future__ import annotations

from typing import Protocol


class HealthMonitorLike(Protocol):
    def observe(self, valence: float, arousal: float, cognitive_load: float, source: str, ts: float) -> None: ...
    def inspect(self): ...


class DriftTrackerLike(Protocol):
    def observe_step(self, tool: str | None, summary: str) -> None: ...
    def heuristic_score(self): ...
    def combined(self, verdict): ...


class PatternMinerLike(Protocol):
    def add(self, task_type: str, succeeded: bool, strategy: str | None, ts: float) -> None: ...
    def mine(self, now: float, **kwargs): ...


class CalibrationTableLike(Protocol):
    def record(self, task_type: str, stated: float, hit: bool) -> None: ...
    def summary(self, task_type: str): ...
