"""Generate `simorgh/interface/splash_art.py` from the official logo.

Dev-only (needs Pillow); the runtime imports only the generated data.
Cells are "half blocks": each text cell shows two vertical pixels via `▀`
with foreground = top pixel and background = bottom pixel, in 24-bit SGR
color. Near-background (cream) pixels become transparent (a plain space),
so the bird floats on whatever the terminal's own background is.

Usage: python3 tools/render_logo_splash.py images/logo/Logo-5.png [cols]
"""
from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image

RESET = "\\x1b[0m"


def _is_background(px, bg, tol=48) -> bool:
    return all(abs(int(a) - int(b)) <= tol for a, b in zip(px, bg))


def main(src: str, cols: int = 52) -> None:
    im = Image.open(src).convert("RGB")
    bg = im.getpixel((2, 2))
    # Crop to the bird's bounding box.
    w, h = im.size
    xs, ys = [], []
    px = im.load()
    for y in range(0, h, 2):
        for x in range(0, w, 2):
            if not _is_background(px[x, y], bg):
                xs.append(x); ys.append(y)
    box = (max(min(xs) - 4, 0), max(min(ys) - 4, 0), min(max(xs) + 5, w), min(max(ys) + 5, h))
    im = im.crop(box)
    # Terminal cells are ~2:1 (tall); a half-block cell covers 1 col x 2 px rows,
    # so scale width to `cols` and height to keep aspect with 2 px per row.
    cw, ch = im.size
    rows = max(2, round(ch / cw * cols / 2 * 2 / 2.0))  # rows of cells
    small = im.resize((cols, rows * 2), Image.LANCZOS)
    sp = small.load()
    out_rows: list[list[tuple]] = []  # per row: list of (top_rgb|None, bottom_rgb|None)
    for r in range(rows):
        row = []
        for c in range(cols):
            top, bot = sp[c, 2 * r], sp[c, 2 * r + 1]
            row.append((None if _is_background(top, bg) else tuple(top),
                        None if _is_background(bot, bg) else tuple(bot)))
        out_rows.append(row)
    # Trim fully-transparent columns on both sides.
    def col_empty(c): return all(row[c] == (None, None) for row in out_rows)
    left = 0
    while left < cols and col_empty(left): left += 1
    right = cols
    while right > left and col_empty(right - 1): right -= 1
    out_rows = [row[left:right] for row in out_rows]

    lines = ['"""Generated by tools/render_logo_splash.py from images/logo/Logo-5.png',
             '(the official Simorgh logo). Do not edit by hand -- re-run the generator.',
             'Each row is a tuple of (top_rgb | None, bottom_rgb | None) half-block cells;',
             'None means transparent (terminal background). Runtime has no image deps."""',
             "", "SOURCE = \"images/logo/Logo-5.png\"", f"WIDTH = {right - left}", "", "ROWS = ("]
    for row in out_rows:
        lines.append("    (" + ", ".join(repr(cell) for cell in row) + ",),")
    lines.append(")")
    Path("simorgh/interface/splash_art.py").write_text("\n".join(lines) + "\n")
    print(f"wrote simorgh/interface/splash_art.py: {right-left} cols x {len(out_rows)} rows")


if __name__ == "__main__":
    main(sys.argv[1], int(sys.argv[2]) if len(sys.argv) > 2 else 52)
