"""Generate `simorgh/interface/splash_art.py` from the official logo.

Dev-only (needs Pillow); the runtime imports only the generated data.
Cells are "half blocks": each text cell shows two vertical pixels via `▀`
with foreground = top pixel and background = bottom pixel, in 24-bit SGR
color. A transparent PNG is used as is (alpha under one half = the terminal's
own background, resampled premultiplied so edges stay clean); a logo on
a solid ground is keyed by tolerance. Lone specks are dropped.

Usage: python3 tools/render_logo_splash.py images/logo/Sim-Logo-transparent.png [cols]
"""
from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image

RESET = "\\x1b[0m"


def _is_background(px, bg, tol=48) -> bool:
    return all(abs(int(a) - int(b)) <= tol for a, b in zip(px, bg))


def main(src: str, cols: int = 52) -> None:
    im = Image.open(src)
    if im.mode != "RGBA" or im.getchannel("A").getextrema()[0] == 255:
        # A logo on a solid ground (the 2026-09-06 files): key the ground out by tolerance.
        rgb = im.convert("RGB")
        bg = rgb.getpixel((2, 2))
        alpha = Image.new("L", rgb.size, 255)
        ap, rp = alpha.load(), rgb.load()
        for y in range(rgb.size[1]):
            for x in range(rgb.size[0]):
                if _is_background(rp[x, y], bg):
                    ap[x, y] = 0
        im = rgb.copy(); im.putalpha(alpha)
    im = im.convert("RGBA")
    im = im.crop(im.getbbox())
    # Terminal cells are ~2:1 (tall); a half-block cell covers 1 col x 2 px rows,
    # so scale width to `cols` and height to keep aspect with 2 px per row.
    cw, ch = im.size
    rows = max(2, round(ch / cw * cols / 2))
    # Premultiplied resampling: a transparent pixel's colour must not bleed into
    # its opaque neighbours, or every edge picks up the checkerboard's grey.
    pre = Image.new("RGBA", im.size)
    pp, ip = pre.load(), im.load()
    for y in range(ch):
        for x in range(cw):
            r, g, b, a = ip[x, y]
            pp[x, y] = (r * a // 255, g * a // 255, b * a // 255, a)
    small = pre.resize((cols, rows * 2), Image.LANCZOS)
    sp = small.load()

    def cell(x, y):
        r, g, b, a = sp[x, y]
        if a < 128:            # a half less than half covered stays the terminal's own background
            return None
        return (min(255, r * 255 // a), min(255, g * 255 // a), min(255, b * 255 // a))

    out_rows: list[list[tuple]] = [[(cell(c, 2 * r), cell(c, 2 * r + 1)) for c in range(cols)] for r in range(rows)]
    # No noise: a lone speck with no painted neighbour is dropped.
    def painted(r, c):
        return 0 <= r < rows and 0 <= c < cols and out_rows[r][c] != (None, None)
    for r in range(rows):
        for c in range(cols):
            if painted(r, c) and not any(painted(r + dr, c + dc) for dr in (-1, 0, 1) for dc in (-1, 0, 1) if (dr, dc) != (0, 0)):
                out_rows[r][c] = (None, None)
    # Trim fully-transparent rows and columns.
    out_rows = [row for row in out_rows if any(cell != (None, None) for cell in row)]
    def col_empty(c): return all(row[c] == (None, None) for row in out_rows)
    left = 0
    while left < cols and col_empty(left): left += 1
    right = cols
    while right > left and col_empty(right - 1): right -= 1
    out_rows = [row[left:right] for row in out_rows]

    lines = [f'"""Generated by tools/render_logo_splash.py from {src}',
             '(the official Simorgh logo). Do not edit by hand -- re-run the generator.',
             'Each row is a tuple of (top_rgb | None, bottom_rgb | None) half-block cells;',
             'None means transparent (terminal background). Runtime has no image deps."""',
             "", f"SOURCE = {src!r}", f"WIDTH = {right - left}", "", "ROWS = ("]
    for row in out_rows:
        lines.append("    (" + ", ".join(repr(cell) for cell in row) + ",),")
    lines.append(")")
    Path("simorgh/interface/splash_art.py").write_text("\n".join(lines) + "\n")
    print(f"wrote simorgh/interface/splash_art.py: {right-left} cols x {len(out_rows)} rows")


if __name__ == "__main__":
    main(sys.argv[1], int(sys.argv[2]) if len(sys.argv) > 2 else 52)
